### ISSUE TITLE
Proposed Roadmap

### ISSUE THREAD

**Issue by canyon289** [aivillage/llm_verification#16]
Jotting down ideas, feel free to edit directly or comment

## Development 
* **Multiturn conversations** - Getting and setting and javascript handle multi turn or single turn, or making a new plugin that is based on this one that does multi turn

## Testing
Simulation of faulty network - Potentially use https://hub.docker.com/r/chaostoolkit/chaostoolkit

**Comment by comath** [comment]
Started working on the multiturn: https://github.com/aivillage/llm_verification/pull/17
